name: genai_env 
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - requests
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - ipywidgets
  - matplotlib
  - scikit-learn
  - jupyter-dash
  - optuna
 
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=12.1
  
  - tensorflow-gpu
  - keras
  
  - pip
  - pip:
    - beautifulsoup4
    - plotly
    - protobuf==5.28.1
    - grpcio==1.68.1
    - grpcio-tools==1.68.1
